version: 2

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Reports suspicious constructs
    - ineffassign   # Detects ineffectual assignments
    - staticcheck   # Advanced go vet
    - unused        # Checks for unused code
    - misspell      # Finds commonly misspelled words
    - revive        # Replacement for golint
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Reports unused function parameters
    - gosec         # Security checks
    - bodyclose     # Checks HTTP response body is closed
    - noctx         # Finds sending HTTP requests without context
    - errname       # Checks error naming conventions
    - errorlint     # Find error wrapping issues
    - gocritic      # Provides diagnostics for bugs, performance, style
    - gocyclo       # Computes cyclomatic complexity
    - dupl          # Code clone detection
    - prealloc      # Find slice declarations that could potentially be preallocated
    - shadow        # Check for shadowed variables

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: var-naming
        severity: warning
        disabled: false
      - name: package-comments
        severity: warning
        disabled: false

  gosec:
    excludes:
      - G104 # Audit errors not checked - covered by errcheck

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - gocritic

    # Exclude known issues
    - text: "weak cryptographic primitive"
      linters:
        - gosec

output:
  formats:
    - colored-line-number
  print-issued-lines: true
  print-linter-name: true
